camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: true
    history-level: full
    id-generator: simple
    database:
      schema-update: false
      type: h2

spring.h2.console.enabled: true

spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate

flyway:
  enabled: true
  locations: "classpath:db"

